apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sowpqkkgy-python 
  janus-idp.io/tekton: sowpqkkgy-python
  backstage.io/kubernetes-id: sowpqkkgy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sowpqkkgy-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml