apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sowpqkkgy-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a22b01b1d2.rdxt.p3.openshiftapps.com/rhtap/rhtap-qe-python:ef5814d969ad56737e171d6bfb201237bddea31d@sha256:f9efedf87ace911b074fcc9ed1abc14725a52d727f600d5beaacd3af31f146e5
          name: container-image
